# -------------------------------------------------------------------#
# Install PHP - latest epel release                                  #
# -------------------------------------------------------------------#

- name: Install PHP on the vm instance
  hosts: 127.0.0.1
  sudo: yes
  gather_facts: no
  connection: local
  
  tasks:
  - name: Install PHP and related modules
    yum: name={{ item }} state=latest update_cache=yes
    with_items:
    - php
    - php-mysql
    - php-gd

  - name: Configure php.ini
    lineinfile:
      dest: /etc/php.ini
      regexp: ^{{ item.key }}\s*=
      state: present
      line: '{{ item.key }} = {{ item.value }}'
    with_items:
      - { key: 'upload_max_filesize', value: '10M' }
      - { key: 'post_max_size', value: '10M' }
      - { key: 'memory_limit', value: '128M' }
      - { key: 'realpath_cache_size', value: '256k' }