# Drush installation

- name: Drush installation
  hosts: localhost
  sudo: yes
  gather_facts: no
  remote_user: vagrant

  tasks:
    # If you can't get php-drush-drush to install, fallback steps can be found at http://www.drush.org/en/master/install/
  - name: Install drush from Yum
    yum: name={{ item }} state=latest update_cache=yes
    with_items:
    - php-drush-drush