# -------------------------------------------------------------------#
# Install httpd webserver - latest epel release                      #
# enable http and https through the firewall                         #
# -------------------------------------------------------------------#

- name: Install and enable httpd service on the vm instance
  hosts: 127.0.0.1
  sudo: yes
  gather_facts: no
  connection: local
  
  tasks:
  - name: Install httpd service
    yum: name=httpd enablerepo=epel state=latest update_cache=yes
    notify: Start and enable httpd services

  - name: Start and enable httpd services
    service: name=httpd state=started enabled=true